#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RotTom.Resource", IsApplication=true)]

namespace RotTom
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fresh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int popcorn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rotten = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int spilt = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MovieRelativeLayout = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int actorImage = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int actorName = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int actorRole = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int criticNamePublication = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int criticScore = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int criticTomato = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int criticsBlurb = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int directorName = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int fragmentContainer = 2131099663;
			
			// aapt resource value: 0x7f060020
			public const int imageView1 = 2131099680;
			
			// aapt resource value: 0x7f060019
			public const int infoBlurb = 2131099673;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout5 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout6 = 2131099668;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout7 = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int movieActors = 2131099652;
			
			// aapt resource value: 0x7f06001e
			public const int movieGenres = 2131099678;
			
			// aapt resource value: 0x7f060001
			public const int movieImage = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int movieTitle = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int ratingAndRuntime = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int relativeLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int relativeLayout2 = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int relativeLayout3 = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int relativeLayout4 = 2131099666;
			
			// aapt resource value: 0x7f06001f
			public const int releaseDate = 2131099679;
			
			// aapt resource value: 0x7f06000d
			public const int reviewText = 2131099661;
			
			// aapt resource value: 0x7f06001a
			public const int scrollView1 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int synopsis = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int userPopcorn = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int usersBlurb = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int usersScore = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BoxOfficeItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CastItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CriticItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int InTheatersItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MovieInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MovieInfoNoScore = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OpeningItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OpeningItemNoScore = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UpcomingItem = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int boxoffice_activity_title = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int boxoffice_tab_title = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int intheaters_tab_title = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int intheatres_activity_title = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int moviecast_tab_title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int moviecritics_tab_title = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int movieinfo_tab_title = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int opening_activity_title = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int opening_tab_title = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int rottentomatoes_api_key = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int upcoming_activity_title = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int upcoming_tab_title = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
